const ShopActionTypes = {
    ON_FETCH_COLLECTIONS_START: "ON_FETCH_COLLECTIONS_START",
    ON_FETCH_COLLECTIONS_SUCCESS: "ON_FETCH_COLLECTIONS_SUCCESS",
    ON_FETCH_COLLECTIONS_FAILURE: "ON_FETCH_COLLECTIONS_FAILURE"
}

export default ShopActionTypes;