const CartActionTypes = {
     TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
     ADD_ITEM: "ADD_ITEM",
     REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
     INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_QUANTITY",
     DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
     CLEAR_CART: "CLEAR_CART",
     SET_CART_FROM_FIREBASE: 'SET_CART_FROM_FIREBASE',
     UPDATE_CART_IN_FIREBASE: 'UPDATE_CART_IN_FIREBASE'
}

export default CartActionTypes;